# Generated by Django 4.1.2 on 2022-10-24 03:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import drones.validators
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('model', models.CharField(choices=[('lightweight', 'Lightweight'), ('middleweight', 'Middleweight'), ('cruiserweight', 'Cruiserweight'), ('heavyweight', 'Heavyweight')], max_length=15)),
                ('weight_limit', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(500, 'The maximum weight limit of a drone is 500gr.')])),
                ('battery_capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'The minimum percentage allowed is 0.'), django.core.validators.MaxValueValidator(100, 'The maximum percentage allowed is 100.')])),
                ('state', models.CharField(choices=[('idle', 'IDLE'), ('loading', 'LOADING'), ('loaded', 'LOADED'), ('delivering', 'DELIVERING'), ('delivered', 'DELIVERED'), ('returning', 'RETURNING')], max_length=10)),
            ],
            options={
                'ordering': ['-battery_capacity'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('[a-zA-Z0-9-_]+'), code='not_allowed_characters', message='It is only allowed letters, numbers, "-" and "_".')])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(1, 'The minimum weight allowed is 1g.')])),
                ('code', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('[A-Z0-9_]+'), code='not_allowed_characters', message='It is only allowed upper-case letters, numbers and "_".')])),
                ('image', models.ImageField(upload_to='medication_pictures/%Y/%m/%d/', validators=[drones.validators.size_validator])),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='drones.drone')),
            ],
        ),
    ]
