# Generated by Django 4.1.2 on 2022-10-29 00:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='drone',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[A-Z0-9_]+$'), code='not_allowed_characters', message='It is only allowed upper-case letters, numbers and "_".')]),
        ),
        migrations.AlterField(
            model_name='medication',
            name='drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drones.drone'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9-_]+$'), code='not_allowed_characters', message='It is only allowed letters, numbers, "-" and "_".')]),
        ),
    ]
